#service1.conf

upstream service01 {
	#server 10.0.10.1:81;
	server ykk-app:8000;
}

server {

	listen 80;
	server_name staging.infrastudy.store;

	location / {
		proxy_pass http://service01;
		
		# Nginx가 백엔드로 요청 보낼 때 HTTP 버전을 1.1로 고정
		# 기본 1.0 (요청마다 연결 끊김) 1.1 (연결 재사용 가능)
		proxy_http_version 1.1;
		# 원래 요청 도메인을 그대로 전달 / backend 도메인 인식가능
		proxy_set_header Host $host;
		# Proxy 서버 IP가 아닌 실제 사용자 IP 전달 (Nginx가 본 바로 그 IP)
		proxy_set_header X-Real-IP $remote_addr;
		# 클라이언트 IP 히스토리 (원래 클라이언트 IP 체인)
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		# http 인지 https 인지 알려줌
		proxy_set_header X-Forwarded-Proto $scheme;

		# GET / POST 만 허용 나머지 차단
		limit_except GET POST {
			deny all;
		}
	}


}