---

# - name: Get DB IP from Terraform
#   delegate_to: localhost
#   command: terraform output -raw instance_db_private_ip
#   args:
#     chdir: ../../02_terraform/envs/01_dev  
#   register: db_ip

- name: Get DB IP from SSM
  delegate_to: localhost
  shell: aws ssm get-parameter --name "/app/db/host" --query "Parameter.Value" --output text
  register: db_ip

- name: Ensure app directory exists
  file:
    path: /home/ykk-admin/app
    state: directory
    owner: ykk-admin
    group: ykk-admin

- name: Check git repo exists
  stat:
    path: /home/ykk-admin/app/.git
  register: git_repo

- name: Clone repo (first time only)
  become_user: ykk-admin
  shell: |
    git clone --no-checkout https://github.com/jinsw1/ykk_team_dev.git /home/ykk-admin/app
  args:
    creates: /home/ykk-admin/app/.git

- name: Enable sparse checkout
  become_user: ykk-admin
  shell: |
    cd /home/ykk-admin/app
    git sparse-checkout init --cone
    git sparse-checkout set 03_docker/was_server

# - name: Checkout was_server as standalone worktree
#   become_user: ykk-admin
#   shell: |
#     git -C /home/ykk-admin/app worktree add /home/ykk-admin/was_server 03_docker/was_server

- name: Fetch latest changes
  become_user: ykk-admin
  shell: |
    cd /home/ykk-admin/app
    git fetch origin main

- name: Reset to latest commit
  become_user: ykk-admin
  shell: |
    cd /home/ykk-admin/app
    git checkout main
    git reset --hard origin/main


- name: Create .env file
  copy:
    dest: /home/ykk-admin/app/03_docker/was_server/.env
    content: |
      ENV={{ env }}
      DB_HOST={{ db_ip.stdout }}
      # DB_USER=scott
      # DB_PASSWORD=tiger
      # DB_NAME=lunch_db
      # DB_PORT=5432


- name: Run docker compose
  become_user: ykk-admin
  shell: |
    cd /home/ykk-admin/app/03_docker/was_server
    docker compose up -d --build