---
# 기존 삭제
- name: Clean db directory
  file:
    path: /home/ykk-admin/db
    state: absent

- name: Create db directory
  file:
    path: /home/ykk-admin/db
    state: directory

# sparse clone
- name: Clone repo without checkout
  ansible.builtin.shell: |
    git clone --no-checkout https://github.com/jinsw1/ykk_team_dev.git /home/ykk-admin/db

# sparse 설정
- name: Enable sparse checkout
  ansible.builtin.shell: |
    cd /home/ykk-admin/db
    git sparse-checkout init --cone
    git sparse-checkout set 03_docker/db_server

# checkout
- name: Checkout branch
  ansible.builtin.shell: |
    cd /home/ykk-admin/db
    git checkout main

# deploy
- name: Run docker compose
  ansible.builtin.shell: |
    cd /home/ykk-admin/app/03_docker/db_server
    docker compose up -d    