#~/ansible/playbooks/site.yml
---
# =================================================================
# [1단계] 모든 서버 공통 환경 및 보안 구성 (KISA 가이드 반영)
# =================================================================
- name: ""
  hosts: all
  become: yes
  roles:
    - role: common

# # =================================================================
# # [2단계] 모든 서버 컨테이너 구동 환경 (Docker) 구축
# # =================================================================
# - hosts: all
#   become: yes
#   roles:
#     - role: docker
#       tags: [docker, base]


- name: ""
  hosts: all
  become: yes
  roles:
    - role: docker

- name: "DB 서버 초기세팅(docker-compose (postgresql 실행))"
  hosts: ykk_db
  roles:
    - role: db_set

- name: "was 서버 초기세팅(docker-compose (nginx/fastapi 실행))"
  hosts: ykk_was
  roles:
    - role: was_set

