
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

	# 서버 정보 숨기기 / 버전노출제한
	server_tokens off;

	# 파일 업로드, 다운로드 용량제한 설정
	# request size 제한 (DDoS / upload 방어)
	client_max_body_size 10M;
	client_header_buffer_size 1k;
	large_client_header_buffers 4 8k;

    server {	
        location / {
			# HTTP method 제한 (전역 수준 옵션)
            limit_except GET POST {
                deny all;
            }
        }
    }

	# 헤더 보안 강화 (필요시 가상호스트 내 직접 지정!!!)
	#add_header X-Content-Type-Options nosniff;
	#add_header X-Frame-Options DENY;
	#add_header X-XSS-Protection "1; mode=block";
	#add_header Referrer-Policy no-referrer-when-downgrade;

	# IP 직접접근 차단 (conf.d/default.conf에 설정)
}
